### ISSUE TITLE
LaunchAppContainer: Example From README No Longer Works

### ISSUE THREAD

**Issue by WildByDesign** [microsoft/SandboxSecurityTools#11]
After the recent addition of the Win32kLockdown mitigation, the example command from LaunchAppContainer README no longer works for `cmd.exe`. I also tried `notepad.exe` and it produced the same error.

Example command from LaunchAppContainer README:

`LaunchAppContainer.exe -m 1.0.0.0_x86_en-us_TestProgram_wvx3sa3v3dj1m -c S-1-15-3-1024-2405443489-874036122-4286035555-1823921565-1746547431-2453885448-3625952902-991631256;S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681 -w -l -i cmd.exe`

Error:

![cmd-error](https://github.com/microsoft/SandboxSecurityTools/assets/26308319/be7b8d14-6b0c-4670-846b-5d757b39d26c)

**Comment by elnx** [comment]
It looks like this commit (https://github.com/microsoft/SandboxSecurityTools/pull/10) is causing the problem?

**Comment by WildByDesign** [comment]
This is fixed and working well since the most recent merged pull request. Thank you.
