### ISSUE TITLE
Interest in adding support for low IL sandboxing?

### ISSUE THREAD

**Issue by forderud** [microsoft/SandboxSecurityTools#8]
Are there any interest in extending this project to also support launching processes in a low integrity level (low IL) process? If so, then I can help contribute on that.

The reason for asking is that I'm currenting maintaining a https://github.com/forderud/RunInSandbox project for launching applications and COM servers in sandboxed processes (either low IL or AppContainer). This project was developed due to the lack of "official" tools for doing so. I would love to retire my project, and instead point to this project if it's extended to become a more complete alternative.

**Comment by rmicelims** [comment]
The main purpose of the SandboxSecurityTools repository is to provide a supported way for external security researchers to test security vulnerability findings in one of the sandboxes eligible for the [Windows Bounty Program](https://www.microsoft.com/en-us/msrc/bounty-windows-insider-preview?rtc=1). While we appreciate your interest in these tools for other purposes, I'm sorry to say that Low IL is not eligible for bounty awards. Therefore, we do not have plans to extend or add support for other technologies that are not part of the Windows Bounty Program.

If you would like to add support for features outside of the scope of this repository, I'd recommend forking the repository for your own development needs.
